[features]
seeds = false
skip-lint = false
[programs.localnet]
create_nft_program = "AHqbhaYrNwAXhH7X4w8cC8y26P2PAATBKzWMnEZP5hnq"
[programs.devnet]
create_nft_program = "AHqbhaYrNwAXhH7X4w8cC8y26P2PAATBKzWMnEZP5hnq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
